import React, { useState } from "react";
import { 
  DataChartType, DataQuestionFocus, DataInterpretationSet, BoardType, DifficultyLevel, UserProfile 
} from "../types";
import { 
  BarChart3, PieChart as PieChartIcon, TrendingUp, Table as TableIcon, GitFork, 
  LayoutGrid, Layers, Sparkles, CheckCircle2, ArrowRight, RefreshCw, 
  Printer, ArrowLeft, Award, HelpCircle, AlertCircle, FileText, Compass, Check
} from "lucide-react";
import jsPDF from "jspdf";

interface DataInterpretationModuleProps {
  user: UserProfile;
  board: BoardType;
  academicLevel: string;
  difficulty: DifficultyLevel;
  onBackToDashboard: () => void;
  onWorksheetCompleted: (score: number, maxScore: number, xp: number) => void;
}

// CURATED SAMPLE DATA SETS (Instant Offline Fallback / Default Library)
const SAMPLE_DATA_SETS: Record<DataChartType, DataInterpretationSet> = {
  "Bar Graph": {
    id: "di_bar_1",
    timestamp: new Date().toISOString(),
    title: "School District Renewable Energy Adoption (2020 - 2024)",
    description: "Annual electricity generated from solar panels (in Megawatt-hours, MWh) across four regional school campuses.",
    chartType: "Bar Graph",
    dataset: {
      summaryText: "Data recorded by the District Environmental Board between 2020 and 2024.",
      categories: ["2020", "2021", "2022", "2023", "2024"],
      series: [
        { name: "North Campus Solar (MWh)", values: [120, 180, 240, 310, 420], color: "#10b981" },
        { name: "South Campus Solar (MWh)", values: [90, 130, 190, 260, 350], color: "#0284c7" }
      ]
    },
    questions: [
      {
        id: 1,
        type: "mcq",
        question: "What was the total solar electricity generated by the North Campus in 2023?",
        options: ["A) 240 MWh", "B) 260 MWh", "C) 310 MWh", "D) 420 MWh"],
        answer: "C) 310 MWh",
        explanation: "Looking directly at the 2023 column for North Campus Solar, the bar value reaches 310 MWh."
      },
      {
        id: 2,
        type: "mcq",
        question: "Calculate the percentage increase in North Campus solar generation from 2020 (120 MWh) to 2024 (420 MWh).",
        options: ["A) 150%", "B) 250%", "C) 300%", "D) 350%"],
        answer: "B) 250%",
        explanation: "Increase = 420 - 120 = 300 MWh. Percentage increase = (300 / 120) * 100 = 250%."
      },
      {
        id: 3,
        type: "mcq",
        question: "What is the ratio of South Campus solar generation in 2021 to 2024?",
        options: ["A) 13 : 35", "B) 9 : 35", "C) 13 : 42", "D) 1 : 3"],
        answer: "A) 13 : 35",
        explanation: "South Campus 2021 = 130 MWh; 2024 = 350 MWh. Ratio = 130 : 350 = 13 : 35."
      },
      {
        id: 4,
        type: "mcq",
        question: "In which year was the difference in generation between North and South campuses the largest?",
        options: ["A) 2020", "B) 2022", "C) 2023", "D) 2024"],
        answer: "D) 2024",
        explanation: "Differences: 2020 = 30 MWh; 2021 = 50 MWh; 2022 = 50 MWh; 2023 = 50 MWh; 2024 = 420 - 350 = 70 MWh (largest)."
      },
      {
        id: 5,
        type: "shortAnswer",
        question: "Based on the 5-year trend, state one valid conclusion about school energy sustainability.",
        options: [],
        answer: "Both campuses show a consistent upward trend in solar adoption, indicating expanding green infrastructure.",
        explanation: "Solar capacity steadily increased every year without exception across both campuses."
      }
    ],
    difficultWords: [
      { word: "Megawatt-hour (MWh)", meaning: "A unit of electric energy equal to 1,000 kilowatt-hours.", contextSentence: "The solar grid produced 420 MWh in 2024." },
      { word: "Adoption Rate", meaning: "The speed or proportion at which new technology is accepted.", contextSentence: "The adoption rate of solar power accelerated after 2021." }
    ],
    learningObjectivesMet: ["Data Interpretation", "Percentage Calculation", "Trend Analysis"],
    curriculumComplianceNotes: "Mapped to National Data Handling and Quantitative Literacy Standards.",
    config: {
      board: "National Standard",
      academicLevel: "Class 8",
      difficulty: "Medium",
      chartType: "Bar Graph",
      questionFocuses: ["Data Reading", "Comparison", "Percentages", "Ratios", "Trends"],
      language: "English"
    }
  },
  "Pie Chart": {
    id: "di_pie_1",
    timestamp: new Date().toISOString(),
    title: "Global Ocean Plastics Origin & Sources Distribution",
    description: "Proportional distribution of marine plastic pollution sources recorded by global oceanic research surveys.",
    chartType: "Pie Chart",
    dataset: {
      summaryText: "Survey compiled by Oceanographic Conservancy.",
      slices: [
        { label: "Single-Use Packaging", value: 45, percentage: 45, color: "#ef4444" },
        { label: "Commercial Fishing Gear", value: 20, percentage: 20, color: "#f59e0b" },
        { label: "Textile Microfibers", value: 15, percentage: 15, color: "#3b82f6" },
        { label: "Industrial Waste", value: 12, percentage: 12, color: "#8b5cf6" },
        { label: "Other Sources", value: 8, percentage: 8, color: "#6b7280" }
      ]
    },
    questions: [
      {
        id: 1,
        type: "mcq",
        question: "Which single category accounts for nearly half (45%) of total ocean plastic pollution?",
        options: ["A) Single-Use Packaging", "B) Commercial Fishing Gear", "C) Textile Microfibers", "D) Industrial Waste"],
        answer: "A) Single-Use Packaging",
        explanation: "Single-Use Packaging accounts for 45% of the pie chart distribution."
      },
      {
        id: 2,
        type: "mcq",
        question: "What combined percentage is contributed by Fishing Gear and Industrial Waste together?",
        options: ["A) 27%", "B) 32%", "C) 35%", "D) 40%"],
        answer: "B) 32%",
        explanation: "Fishing Gear (20%) + Industrial Waste (12%) = 32%."
      },
      {
        id: 3,
        type: "mcq",
        question: "Find the ratio between Commercial Fishing Gear and Textile Microfibers.",
        options: ["A) 3 : 4", "B) 4 : 3", "C) 2 : 1", "D) 5 : 3"],
        answer: "B) 4 : 3",
        explanation: "Fishing Gear = 20%, Textile Microfibers = 15%. Ratio = 20 : 15 = 4 : 3."
      },
      {
        id: 4,
        type: "mcq",
        question: "If a ocean cleanup mission recovers 500 metric tons of waste, approximately how many tons are Single-Use Packaging?",
        options: ["A) 180 tons", "B) 225 tons", "C) 250 tons", "D) 300 tons"],
        answer: "B) 225 tons",
        explanation: "45% of 500 tons = 0.45 * 500 = 225 metric tons."
      }
    ],
    difficultWords: [
      { word: "Proportional Distribution", meaning: "Division of a whole into relative percentage parts.", contextSentence: "The pie chart displays the proportional distribution of waste sources." }
    ],
    learningObjectivesMet: ["Proportional Reasoning", "Pie Chart Analysis", "Environmental Literacy"],
    curriculumComplianceNotes: "Standards-compliant environmental data representation.",
    config: {
      board: "National Standard",
      academicLevel: "Class 8",
      difficulty: "Medium",
      chartType: "Pie Chart",
      questionFocuses: ["Data Reading", "Percentages", "Ratios"],
      language: "English"
    }
  },
  "Line Graph": {
    id: "di_line_1",
    timestamp: new Date().toISOString(),
    title: "Global Digital Literacy Index Growth (2018 - 2025)",
    description: "Average proficiency scores (out of 100) measured across rural vs urban educational sectors.",
    chartType: "Line Graph",
    dataset: {
      summaryText: "Collected by the National Educational Technology Benchmark.",
      categories: ["2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025"],
      series: [
        { name: "Urban Schools Score", values: [55, 60, 68, 75, 82, 88, 92, 95], color: "#2563eb" },
        { name: "Rural Schools Score", values: [30, 36, 45, 58, 67, 76, 83, 89], color: "#d97706" }
      ]
    },
    questions: [
      {
        id: 1,
        type: "mcq",
        question: "What was the digital literacy score gap between Urban and Rural schools in 2018?",
        options: ["A) 15 points", "B) 20 points", "C) 25 points", "D) 30 points"],
        answer: "C) 25 points",
        explanation: "In 2018: Urban = 55, Rural = 30. Gap = 55 - 30 = 25 points."
      },
      {
        id: 2,
        type: "mcq",
        question: "In 2025, what is the score gap between Urban and Rural schools?",
        options: ["A) 6 points", "B) 9 points", "C) 12 points", "D) 15 points"],
        answer: "A) 6 points",
        explanation: "In 2025: Urban = 95, Rural = 89. Gap = 95 - 89 = 6 points."
      },
      {
        id: 3,
        type: "mcq",
        question: "Which sector demonstrated a faster absolute point growth between 2018 and 2025?",
        options: ["A) Urban Schools (+40)", "B) Rural Schools (+59)", "C) Both grew equally", "D) Neither sector grew"],
        answer: "B) Rural Schools (+59)",
        explanation: "Urban growth = 95 - 55 = +40 points. Rural growth = 89 - 30 = +59 points."
      }
    ],
    difficultWords: [
      { word: "Proficiency Index", meaning: "A numerical rating indicating competence or mastery in a skill.", contextSentence: "The literacy index tracks student digital mastery over time." }
    ],
    learningObjectivesMet: ["Line Chart Trend Interpretation", "Rate of Change Analysis"],
    curriculumComplianceNotes: "Quantitative literacy and technological trends benchmark.",
    config: {
      board: "National Standard",
      academicLevel: "Class 8",
      difficulty: "Medium",
      chartType: "Line Graph",
      questionFocuses: ["Trends", "Comparison", "Inference"],
      language: "English"
    }
  },
  "Table": {
    id: "di_table_1",
    timestamp: new Date().toISOString(),
    title: "Agricultural Crop Yield & Irrigation Efficiency Matrix",
    description: "Comparative study of five major staple crops under organic drip irrigation vs flood irrigation.",
    chartType: "Table",
    dataset: {
      summaryText: "Data published by the Agricultural Research Council.",
      headers: ["Crop Name", "Drip Yield (Tons/Hectare)", "Flood Yield (Tons/Hectare)", "Water Savings (%)", "Market Value ($/Ton)"],
      rows: [
        ["Wheat", "4.8", "3.6", "42%", "$280"],
        ["Rice", "5.2", "4.5", "35%", "$340"],
        ["Maize (Corn)", "6.1", "4.2", "48%", "$220"],
        ["Soybean", "3.4", "2.8", "50%", "$450"],
        ["Pulses (Lentils)", "2.9", "2.1", "55%", "$610"]
      ]
    },
    questions: [
      {
        id: 1,
        type: "mcq",
        question: "Which crop achieves the highest percentage of water savings with drip irrigation?",
        options: ["A) Wheat", "B) Maize", "C) Soybean", "D) Pulses (Lentils)"],
        answer: "D) Pulses (Lentils)",
        explanation: "Looking at the Water Savings (%) column: Pulses shows 55%, the highest among all crops."
      },
      {
        id: 2,
        type: "mcq",
        question: "Calculate the revenue generated per hectare for Maize under drip irrigation (6.1 Tons/Hectare at $220/Ton).",
        options: ["A) $1,242", "B) $1,342", "C) $1,440", "D) $1,520"],
        answer: "B) $1,342",
        explanation: "Revenue = Yield * Market Value = 6.1 * 220 = $1,342."
      }
    ],
    difficultWords: [
      { word: "Hectare", meaning: "A metric unit of square measure equal to 10,000 square meters.", contextSentence: "The field produced 4.8 tons of wheat per hectare." }
    ],
    learningObjectivesMet: ["Tabular Data Extraction", "Multi-Variable Matrix Analysis"],
    curriculumComplianceNotes: "Applied mathematics and agricultural economics mapping.",
    config: {
      board: "National Standard",
      academicLevel: "Class 8",
      difficulty: "Medium",
      chartType: "Table",
      questionFocuses: ["Data Reading", "Comparison", "Logical Reasoning"],
      language: "English"
    }
  },
  "Flow Chart": {
    id: "di_flow_1",
    timestamp: new Date().toISOString(),
    title: "Scholastic Article Peer-Review & Publication Protocol",
    description: "Step-by-step editorial pathway governing scientific article submission and verification.",
    chartType: "Flow Chart",
    dataset: {
      summaryText: "Official procedure manual for Academic Publishing.",
      flowSteps: [
        { step: 1, title: "Initial Manuscript Submission", description: "Author submits research document to Editorial Board.", type: "start" },
        { step: 2, title: "Desk Review & Screening", description: "Editor verifies scope, formatting, and plagiarism checks.", type: "process" },
        { step: 3, title: "Double-Blind Peer Review", description: "Sent to 3 independent domain experts for evaluation.", type: "process" },
        { step: 4, title: "Revisions Needed?", description: "Decision node: Major revisions required or approved.", type: "decision" },
        { step: 5, title: "Final Proofing & Indexing", description: "Article typeset and published in Digital Library.", type: "end" }
      ]
    },
    questions: [
      {
        id: 1,
        type: "mcq",
        question: "How many independent domain experts evaluate the manuscript in Step 3?",
        options: ["A) 1 expert", "B) 2 experts", "C) 3 experts", "D) 5 experts"],
        answer: "C) 3 experts",
        explanation: "Step 3 specifies 'Sent to 3 independent domain experts for evaluation'."
      },
      {
        id: 2,
        type: "mcq",
        question: "Which step functions as a decision node determining if revisions are mandatory?",
        options: ["A) Step 2", "B) Step 3", "C) Step 4", "D) Step 5"],
        answer: "C) Step 4",
        explanation: "Step 4 is the Decision node ('Revisions Needed?')."
      }
    ],
    difficultWords: [
      { word: "Double-Blind Review", meaning: "A review process where both author and reviewer identities are hidden.", contextSentence: "Double-blind peer review ensures unbiased evaluation." }
    ],
    learningObjectivesMet: ["Flowchart Reading", "Process Hierarchy Logic"],
    curriculumComplianceNotes: "Logical flow and structural process analysis.",
    config: {
      board: "National Standard",
      academicLevel: "Class 8",
      difficulty: "Medium",
      chartType: "Flow Chart",
      questionFocuses: ["Logical Reasoning", "Conclusions"],
      language: "English"
    }
  },
  "Infographic": {
    id: "di_info_1",
    timestamp: new Date().toISOString(),
    title: "Deep-Space Exploration & Lunar Base Key Metrics",
    description: "Key performance figures and technological milestones for the Artemis Lunar Outpost.",
    chartType: "Infographic",
    dataset: {
      summaryText: "Published by Space Exploration Operations Command.",
      infographicNodes: [
        { title: "Solar Power Capacity", stat: "120 kW", subtext: "Continuous clean energy from surface panels", badge: "ENERGY" },
        { title: "Water Recycling Efficiency", stat: "98.4%", subtext: "Closed-loop atmospheric & liquid recovery", badge: "SUSTAINABILITY" },
        { title: "Crew Capacity", stat: "6 Astronauts", subtext: "Long-duration 180-day rotation shifts", badge: "HABITAT" },
        { title: "Lunar Rover Range", stat: "250 km", subtext: "Autonomous battery-operated surface exploration", badge: "MOBILITY" }
      ]
    },
    questions: [
      {
        id: 1,
        type: "mcq",
        question: "What is the water recycling efficiency achieved at the Lunar Outpost?",
        options: ["A) 85%", "B) 92%", "C) 98.4%", "D) 100%"],
        answer: "C) 98.4%",
        explanation: "The Infographic metric explicitly states 98.4% closed-loop recovery."
      },
      {
        id: 2,
        type: "mcq",
        question: "If a rover completes a round-trip exploration mission of 120 km, what percentage of its maximum 250 km range was utilized?",
        options: ["A) 40%", "B) 48%", "C) 52%", "D) 60%"],
        answer: "B) 48%",
        explanation: "(120 / 250) * 100 = 48%."
      }
    ],
    difficultWords: [
      { word: "Closed-loop", meaning: "A system where waste products are continuously recycled.", contextSentence: "The closed-loop recycling system saves vital water." }
    ],
    learningObjectivesMet: ["Infographic Data Extraction", "Key Metric Synthesis"],
    curriculumComplianceNotes: "Modern visual data literacy and STEM metric interpretation.",
    config: {
      board: "National Standard",
      academicLevel: "Class 8",
      difficulty: "Medium",
      chartType: "Infographic",
      questionFocuses: ["Data Reading", "Percentages", "Inference"],
      language: "English"
    }
  },
  "Mixed Data Set": {
    id: "di_mixed_1",
    timestamp: new Date().toISOString(),
    title: "National Telecommunications Fiber Grid Expansion & Subscriber Revenue",
    description: "Combined data set featuring 5-year subscriber growth bar graph alongside regional maintenance cost table.",
    chartType: "Mixed Data Set",
    dataset: {
      summaryText: "Multi-modal analysis report by the Telecom Regulatory Authority.",
      categories: ["2021", "2022", "2023", "2024"],
      series: [
        { name: "Fiber Connections (Millions)", values: [12, 18, 26, 38], color: "#0d9488" }
      ],
      headers: ["Region", "Fiber Lines (km)", "Annual Cost ($M)", "Cost per km ($)"],
      rows: [
        ["North", "45,000", "$90M", "$2,000"],
        ["South", "60,000", "$108M", "$1,800"],
        ["East", "30,000", "$75M", "$2,500"],
        ["West", "50,000", "$95M", "$1,900"]
      ]
    },
    questions: [
      {
        id: 1,
        type: "mcq",
        question: "Based on the Bar Graph, what was the total increase in fiber connections from 2021 (12M) to 2024 (38M)?",
        options: ["A) 18 Million", "B) 22 Million", "C) 26 Million", "D) 30 Million"],
        answer: "C) 26 Million",
        explanation: "38M - 12M = 26 Million connections increase."
      },
      {
        id: 2,
        type: "mcq",
        question: "Looking at the Maintenance Cost Table, which region has the lowest maintenance cost per kilometer of fiber line?",
        options: ["A) North ($2,000)", "B) South ($1,800)", "C) East ($2,500)", "D) West ($1,900)"],
        answer: "B) South ($1,800)",
        explanation: "The South region has the lowest unit cost at $1,800 per km."
      }
    ],
    difficultWords: [
      { word: "Subscribers", meaning: "Customers who pay regularly for a service like internet or telecom.", contextSentence: "Fiber subscribers rose to 38 million." }
    ],
    learningObjectivesMet: ["Multi-Modal Data Synthesis", "Comparative Economics"],
    curriculumComplianceNotes: "Advanced multi-source data interpretation framework.",
    config: {
      board: "National Standard",
      academicLevel: "Class 8",
      difficulty: "Medium",
      chartType: "Mixed Data Set",
      questionFocuses: ["Data Reading", "Comparison", "Percentages", "Logical Reasoning"],
      language: "English"
    }
  }
};

export default function DataInterpretationModule({
  user,
  board,
  academicLevel,
  difficulty,
  onBackToDashboard,
  onWorksheetCompleted
}: DataInterpretationModuleProps) {

  // State
  const [selectedChartType, setSelectedChartType] = useState<DataChartType>("Bar Graph");
  const [activeDataSet, setActiveDataSet] = useState<DataInterpretationSet>(SAMPLE_DATA_SETS["Bar Graph"]);
  const [selectedFocuses, setSelectedFocuses] = useState<DataQuestionFocus[]>([
    "Data Reading", "Comparison", "Percentages", "Trends"
  ]);

  // Solver States
  const [userAnswers, setUserAnswers] = useState<Record<number, string>>({});
  const [submitted, setSubmitted] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [scoreResult, setScoreResult] = useState<{ score: number; max: number; percentage: number; xp: number } | null>(null);

  // Available chart options
  const chartOptions: { type: DataChartType; label: string; desc: string; icon: any }[] = [
    { type: "Bar Graph", label: "Bar Graph", desc: "Comparative bar column charts across categories", icon: BarChart3 },
    { type: "Pie Chart", label: "Pie Chart", desc: "Proportional distribution & percentage slices", icon: PieChartIcon },
    { type: "Line Graph", label: "Line Graph", desc: "Time series trends & trajectory lines", icon: TrendingUp },
    { type: "Table", label: "Data Table", desc: "Multi-column structured data rows & metrics", icon: TableIcon },
    { type: "Flow Chart", label: "Flow Chart", desc: "Sequential process diagrams & decision paths", icon: GitFork },
    { type: "Infographic", label: "Infographic", desc: "Metric card highlights & key performance stats", icon: LayoutGrid },
    { type: "Mixed Data Set", label: "Mixed Data Set", desc: "Multi-modal combined charts & tabular data", icon: Layers }
  ];

  // Question focuses
  const focusList: DataQuestionFocus[] = [
    "Data Reading", "Comparison", "Percentages", "Ratios", "Trends", "Logical Reasoning", "Inference", "Conclusions"
  ];

  // Handle Chart Type Switching
  const handleSelectChartType = (type: DataChartType) => {
    setSelectedChartType(type);
    setUserAnswers({});
    setSubmitted(false);
    setScoreResult(null);
    if (SAMPLE_DATA_SETS[type]) {
      setActiveDataSet(SAMPLE_DATA_SETS[type]);
    }
  };

  // Toggle question focus
  const toggleFocus = (focus: DataQuestionFocus) => {
    if (selectedFocuses.includes(focus)) {
      if (selectedFocuses.length > 1) {
        setSelectedFocuses(selectedFocuses.filter(f => f !== focus));
      }
    } else {
      setSelectedFocuses([...selectedFocuses, focus]);
    }
  };

  // Call API for Custom AI Generation
  const handleGenerateCustomSet = async () => {
    setGenerating(true);
    setUserAnswers({});
    setSubmitted(false);
    setScoreResult(null);

    try {
      let data: any = null;
      try {
        const response = await fetch("/api/generate-data-interpretation", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            board,
            academicLevel: academicLevel || "Class 8",
            difficulty,
            chartType: selectedChartType,
            questionFocuses: selectedFocuses,
            language: "English"
          })
        });

        const resText = await response.text();
        if (resText && resText.trim().length > 0) {
          try {
            data = JSON.parse(resText);
          } catch (_) {}
        }
      } catch (fetchErr) {
        console.warn("DI generation API error, using sample data fallback:", fetchErr);
      }

      if (data && data.questions && data.questions.length > 0) {
        setActiveDataSet(data);
      } else if (SAMPLE_DATA_SETS[selectedChartType]) {
        setActiveDataSet(SAMPLE_DATA_SETS[selectedChartType]);
      }
    } catch (err) {
      console.warn("Falling back to sample set due to API error:", err);
      if (SAMPLE_DATA_SETS[selectedChartType]) {
        setActiveDataSet(SAMPLE_DATA_SETS[selectedChartType]);
      }
    } finally {
      setGenerating(false);
    }
  };

  // Handle Answer Selection
  const handleOptionSelect = (qId: number, option: string) => {
    if (submitted) return;
    setUserAnswers(prev => ({ ...prev, [qId]: option }));
  };

  // Submit Answer Evaluation
  const handleSubmitWorksheet = () => {
    let score = 0;
    const maxScore = activeDataSet.questions.length;

    activeDataSet.questions.forEach(q => {
      const given = userAnswers[q.id] || "";
      if (q.type === "mcq") {
        if (given.trim().toLowerCase() === q.answer.trim().toLowerCase()) {
          score++;
        }
      } else {
        if (given.trim().length > 3) {
          score++; // Award for descriptive attempts in practice mode
        }
      }
    });

    const percentage = Math.round((score / maxScore) * 100);
    const xpGained = score * 25 + 50;
    setScoreResult({ score, max: maxScore, percentage, xp: xpGained });
    setSubmitted(true);

    onWorksheetCompleted(score, maxScore, xpGained);
  };

  // Print PDF
  const handlePrintPDF = () => {
    const doc = new jsPDF({ unit: "pt", format: "letter" });
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("COMPREVO — Data Interpretation Worksheet", 40, 50);

    doc.setFontSize(12);
    doc.text(`Title: ${activeDataSet.title}`, 40, 75);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.text(`Level: ${academicLevel || "Class 8"} | Board: ${board} | Type: ${activeDataSet.chartType}`, 40, 95);

    let y = 120;
    doc.setFont("helvetica", "bold");
    doc.text("Description & Overview:", 40, y);
    y += 15;
    doc.setFont("helvetica", "normal");
    const descLines = doc.splitTextToSize(activeDataSet.description, 520);
    doc.text(descLines, 40, y);
    y += descLines.length * 12 + 20;

    doc.setFont("helvetica", "bold");
    doc.text("Questions:", 40, y);
    y += 15;

    activeDataSet.questions.forEach((q, idx) => {
      if (y > 700) {
        doc.addPage();
        y = 50;
      }
      doc.setFont("helvetica", "bold");
      doc.text(`Q${idx + 1}. ${q.question}`, 40, y);
      y += 14;

      if (q.options && q.options.length > 0) {
        doc.setFont("helvetica", "normal");
        q.options.forEach(opt => {
          doc.text(`   ${opt}`, 40, y);
          y += 12;
        });
      }
      y += 10;
    });

    doc.save(`${activeDataSet.title.replace(/\s+/g, "_")}_Data_Worksheet.pdf`);
  };

  return (
    <div className="space-y-8 animate-fadeIn" id="data-interpretation-container">
      
      {/* HEADER BAR */}
      <div className="flex flex-col md:flex-row md:items-center justify-between border-b border-zinc-200/60 dark:border-zinc-800/60 pb-6 gap-4">
        <div className="space-y-1 text-left">
          <div className="flex items-center space-x-2">
            <button 
              onClick={onBackToDashboard}
              className="inline-flex items-center space-x-1 text-xs text-zinc-500 hover:text-zinc-800 dark:hover:text-zinc-200 transition cursor-pointer"
            >
              <ArrowLeft className="h-3.5 w-3.5" />
              <span>Dashboard</span>
            </button>
            <span className="text-zinc-300 dark:text-zinc-700">&bull;</span>
            <span className="text-[10px] font-mono font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-widest">
              Quantitative Reasoning Module
            </span>
          </div>
          <h2 className="font-display text-2xl md:text-3xl font-bold text-zinc-900 dark:text-white tracking-tight flex items-center gap-2">
            Data Interpretation Workspace
          </h2>
          <p className="text-xs text-zinc-500 dark:text-zinc-450 leading-relaxed max-w-2xl">
            Master bar graphs, pie charts, line graphs, data tables, flowcharts, and infographics through diagnostic reasoning questions.
          </p>
        </div>

        <div className="flex items-center space-x-2 shrink-0">
          <button
            onClick={handlePrintPDF}
            className="inline-flex items-center space-x-1.5 px-3.5 py-2 rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 text-zinc-700 dark:text-zinc-200 text-xs font-semibold hover:bg-zinc-50 dark:hover:bg-zinc-850 transition cursor-pointer"
          >
            <Printer className="h-3.5 w-3.5 text-emerald-600" />
            <span>Export PDF</span>
          </button>
          <button
            onClick={handleGenerateCustomSet}
            disabled={generating}
            className="inline-flex items-center space-x-1.5 px-4 py-2 rounded-lg bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold shadow-sm transition cursor-pointer disabled:opacity-50"
          >
            <Sparkles className={`h-3.5 w-3.5 ${generating ? "animate-spin" : ""}`} />
            <span>{generating ? "Generating AI Set..." : "New AI Data Set"}</span>
          </button>
        </div>
      </div>

      {/* CHART TYPE SELECTION BAR */}
      <div className="space-y-3">
        <label className="text-[10px] font-mono font-bold tracking-widest text-zinc-400 dark:text-zinc-500 uppercase block">
          Select Data Representation Type
        </label>
        <div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-2.5">
          {chartOptions.map(opt => {
            const IconComponent = opt.icon;
            const active = selectedChartType === opt.type;
            return (
              <button
                key={opt.type}
                onClick={() => handleSelectChartType(opt.type)}
                className={`p-3 rounded-xl border text-left flex flex-col justify-between transition cursor-pointer ${
                  active 
                    ? "border-emerald-600 bg-emerald-50/50 dark:bg-emerald-950/20 text-emerald-900 dark:text-emerald-300 ring-1 ring-emerald-600/30" 
                    : "border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900 text-zinc-700 dark:text-zinc-300 hover:border-zinc-300 dark:hover:border-zinc-700"
                }`}
              >
                <div className="flex items-center justify-between mb-2">
                  <IconComponent className={`h-4 w-4 ${active ? "text-emerald-600 dark:text-emerald-400" : "text-zinc-400"}`} />
                  {active && <Check className="h-3.5 w-3.5 text-emerald-600 dark:text-emerald-400" />}
                </div>
                <div>
                  <div className="text-xs font-bold font-sans tracking-tight">{opt.label}</div>
                  <div className="text-[9px] text-zinc-400 dark:text-zinc-500 line-clamp-1 mt-0.5">{opt.desc}</div>
                </div>
              </button>
            );
          })}
        </div>
      </div>

      {/* QUESTION FOCUSES BAR */}
      <div className="bg-zinc-50 dark:bg-zinc-900/50 rounded-xl p-4 border border-zinc-200/80 dark:border-zinc-800/80 space-y-2">
        <span className="text-[9px] font-mono font-bold text-zinc-400 dark:text-zinc-500 uppercase tracking-widest block">
          Target Question Categories
        </span>
        <div className="flex flex-wrap gap-2">
          {focusList.map(f => {
            const selected = selectedFocuses.includes(f);
            return (
              <button
                key={f}
                onClick={() => toggleFocus(f)}
                className={`px-3 py-1 rounded-lg text-xs font-medium transition cursor-pointer flex items-center gap-1.5 ${
                  selected 
                    ? "bg-zinc-900 text-white dark:bg-zinc-100 dark:text-zinc-900 shadow-xs" 
                    : "bg-white dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400 border border-zinc-200 dark:border-zinc-700 hover:border-zinc-300"
                }`}
              >
                <span>{f}</span>
                {selected && <Check className="h-3 w-3" />}
              </button>
            );
          })}
        </div>
      </div>

      {/* MAIN DATA INTERPRETATION DISPLAY & SOLVER GRID */}
      <div className="grid gap-8 lg:grid-cols-12">
        
        {/* LEFT COLUMN: VISUAL DATA RENDERER (Col-7) */}
        <div className="lg:col-span-7 space-y-6">
          <div className="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900 shadow-xs space-y-5">
            
            <div className="flex items-start justify-between gap-4 border-b border-zinc-100 dark:border-zinc-800 pb-4">
              <div>
                <span className="text-[9px] font-mono font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-widest px-2 py-0.5 rounded bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-100 dark:border-emerald-900/30">
                  {activeDataSet.chartType} Representation
                </span>
                <h3 className="font-display text-xl font-bold text-zinc-900 dark:text-white mt-1.5">
                  {activeDataSet.title}
                </h3>
                <p className="text-xs text-zinc-500 dark:text-zinc-400 mt-1 leading-relaxed">
                  {activeDataSet.description}
                </p>
              </div>
            </div>

            {/* VISUAL CHART INTERACTIVE DISPLAY */}
            <div className="p-4 rounded-xl bg-zinc-50 dark:bg-zinc-950 border border-zinc-200/60 dark:border-zinc-800/60 min-h-[300px] flex flex-col justify-center">
              
              {/* BAR GRAPH */}
              {activeDataSet.chartType === "Bar Graph" && activeDataSet.dataset.categories && (
                <div className="space-y-6">
                  <div className="space-y-4">
                    {activeDataSet.dataset.categories.map((cat, idx) => {
                      return (
                        <div key={cat} className="space-y-1.5">
                          <div className="text-xs font-semibold text-zinc-700 dark:text-zinc-300 flex justify-between">
                            <span>{cat}</span>
                          </div>
                          <div className="grid gap-1.5">
                            {(activeDataSet.dataset.series || []).map((s, sIdx) => {
                              const val = s.values[idx] || 0;
                              const maxVal = Math.max(...(activeDataSet.dataset.series || []).flatMap(x => x.values), 100);
                              const pct = Math.min(100, Math.round((val / maxVal) * 100));
                              return (
                                <div key={sIdx} className="space-y-0.5">
                                  <div className="flex items-center justify-between text-[10px] text-zinc-500 dark:text-zinc-400 font-mono">
                                    <span>{s.name}</span>
                                    <span className="font-bold">{val}</span>
                                  </div>
                                  <div className="h-4 w-full bg-zinc-200 dark:bg-zinc-800 rounded-md overflow-hidden relative">
                                    <div 
                                      className="h-full transition-all duration-700 rounded-md flex items-center justify-end pr-2 text-[9px] font-bold text-white"
                                      style={{ width: `${pct}%`, backgroundColor: s.color || (sIdx === 0 ? "#10b981" : "#0284c7") }}
                                    >
                                      {val}
                                    </div>
                                  </div>
                                </div>
                              );
                            })}
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              )}

              {/* PIE CHART */}
              {activeDataSet.chartType === "Pie Chart" && activeDataSet.dataset.slices && (
                <div className="grid md:grid-cols-2 gap-6 items-center">
                  <div className="flex justify-center">
                    <svg viewBox="0 0 100 100" className="w-48 h-48 transform -rotate-90">
                      {(() => {
                        let cumulativePercent = 0;
                        return activeDataSet.dataset.slices!.map((slice, i) => {
                          const startPercent = cumulativePercent;
                          cumulativePercent += slice.percentage || (slice.value / 100) * 100;
                          const x1 = Math.cos(2 * Math.PI * startPercent / 100) * 40 + 50;
                          const y1 = Math.sin(2 * Math.PI * startPercent / 100) * 40 + 50;
                          const x2 = Math.cos(2 * Math.PI * cumulativePercent / 100) * 40 + 50;
                          const y2 = Math.sin(2 * Math.PI * cumulativePercent / 100) * 40 + 50;
                          const largeArcFlag = slice.percentage! > 50 ? 1 : 0;
                          const pathData = `M 50 50 L ${x1} ${y1} A 40 40 0 ${largeArcFlag} 1 ${x2} ${y2} Z`;
                          return (
                            <path
                              key={i}
                              d={pathData}
                              fill={slice.color || ["#ef4444", "#f59e0b", "#3b82f6", "#8b5cf6", "#10b981"][i % 5]}
                              className="hover:opacity-80 transition cursor-pointer stroke-white dark:stroke-zinc-900 stroke-2"
                            />
                          );
                        });
                      })()}
                    </svg>
                  </div>
                  <div className="space-y-2">
                    {activeDataSet.dataset.slices.map((slice, i) => (
                      <div key={i} className="flex items-center justify-between text-xs p-2 rounded-lg bg-white dark:bg-zinc-900 border border-zinc-200/50 dark:border-zinc-800">
                        <div className="flex items-center space-x-2">
                          <div className="h-3 w-3 rounded-full shrink-0" style={{ backgroundColor: slice.color || ["#ef4444", "#f59e0b", "#3b82f6", "#8b5cf6", "#10b981"][i % 5] }} />
                          <span className="font-semibold text-zinc-800 dark:text-zinc-200">{slice.label}</span>
                        </div>
                        <span className="font-mono font-bold text-zinc-900 dark:text-white">{slice.percentage || slice.value}%</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* LINE GRAPH */}
              {activeDataSet.chartType === "Line Graph" && activeDataSet.dataset.categories && (
                <div className="space-y-4">
                  <div className="h-48 flex items-end justify-between border-b border-l border-zinc-300 dark:border-zinc-700 p-4 relative">
                    {(activeDataSet.dataset.series || []).map((s, sIdx) => {
                      const maxVal = Math.max(...(activeDataSet.dataset.series || []).flatMap(x => x.values), 100);
                      return (
                        <div key={sIdx} className="absolute inset-x-8 bottom-4 top-4 flex items-end justify-between pointer-events-none">
                          {s.values.map((val, vIdx) => {
                            const heightPct = Math.round((val / maxVal) * 100);
                            return (
                              <div key={vIdx} className="flex flex-col items-center group pointer-events-auto">
                                <div className="text-[9px] font-mono font-bold text-zinc-600 dark:text-zinc-300 mb-1 opacity-80 group-hover:opacity-100">
                                  {val}
                                </div>
                                <div 
                                  className="w-3 rounded-t-full transition-all duration-500" 
                                  style={{ height: `${heightPct}%`, backgroundColor: s.color || (sIdx === 0 ? "#2563eb" : "#d97706") }}
                                />
                              </div>
                            );
                          })}
                        </div>
                      );
                    })}
                  </div>
                  <div className="flex justify-between px-8 text-[10px] font-mono text-zinc-500">
                    {activeDataSet.dataset.categories.map(c => <span key={c}>{c}</span>)}
                  </div>
                  <div className="flex flex-wrap gap-4 pt-2 border-t border-zinc-200 dark:border-zinc-800 justify-center">
                    {(activeDataSet.dataset.series || []).map((s, idx) => (
                      <div key={idx} className="flex items-center space-x-1.5 text-xs font-medium text-zinc-700 dark:text-zinc-300">
                        <span className="h-2.5 w-2.5 rounded-full" style={{ backgroundColor: s.color || (idx === 0 ? "#2563eb" : "#d97706") }} />
                        <span>{s.name}</span>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* DATA TABLE */}
              {(activeDataSet.chartType === "Table" || activeDataSet.chartType === "Mixed Data Set") && activeDataSet.dataset.headers && (
                <div className="overflow-x-auto rounded-xl border border-zinc-200 dark:border-zinc-800">
                  <table className="w-full text-left text-xs">
                    <thead className="bg-zinc-100 dark:bg-zinc-850 text-zinc-800 dark:text-zinc-200 font-bold uppercase tracking-wider font-mono text-[10px]">
                      <tr>
                        {activeDataSet.dataset.headers.map((h, i) => (
                          <th key={i} className="p-3 border-b border-zinc-200 dark:border-zinc-800">{h}</th>
                        ))}
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-zinc-200 dark:divide-zinc-800 text-zinc-700 dark:text-zinc-300">
                      {(activeDataSet.dataset.rows || []).map((row, rIdx) => (
                        <tr key={rIdx} className="hover:bg-zinc-100/50 dark:hover:bg-zinc-850/50 transition">
                          {row.map((cell, cIdx) => (
                            <td key={cIdx} className="p-3 font-sans">{cell}</td>
                          ))}
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              )}

              {/* FLOW CHART */}
              {activeDataSet.chartType === "Flow Chart" && activeDataSet.dataset.flowSteps && (
                <div className="space-y-3 my-2">
                  {activeDataSet.dataset.flowSteps.map((step) => (
                    <div key={step.step} className="flex items-center space-x-3">
                      <div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-emerald-600 text-white font-mono text-xs font-bold">
                        {step.step}
                      </div>
                      <div className="flex-1 p-3 rounded-xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 shadow-2xs">
                        <div className="font-bold text-xs text-zinc-900 dark:text-white">{step.title}</div>
                        <div className="text-[11px] text-zinc-500 dark:text-zinc-400">{step.description}</div>
                      </div>
                    </div>
                  ))}
                </div>
              )}

              {/* INFOGRAPHIC */}
              {activeDataSet.chartType === "Infographic" && activeDataSet.dataset.infographicNodes && (
                <div className="grid sm:grid-cols-2 gap-3">
                  {activeDataSet.dataset.infographicNodes.map((node, i) => (
                    <div key={i} className="p-4 rounded-xl bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 space-y-1">
                      {node.badge && (
                        <span className="text-[8px] font-mono font-bold uppercase tracking-widest text-emerald-600 dark:text-emerald-400 bg-emerald-50 dark:bg-emerald-950/30 px-2 py-0.5 rounded">
                          {node.badge}
                        </span>
                      )}
                      <div className="text-2xl font-black font-mono text-zinc-900 dark:text-white pt-1">{node.stat}</div>
                      <div className="font-bold text-xs text-zinc-800 dark:text-zinc-200">{node.title}</div>
                      <div className="text-[10px] text-zinc-500 dark:text-zinc-400">{node.subtext}</div>
                    </div>
                  ))}
                </div>
              )}

              {activeDataSet.dataset.summaryText && (
                <div className="mt-4 p-3 rounded-lg bg-emerald-500/5 border border-emerald-500/20 text-[11px] text-emerald-900 dark:text-emerald-300">
                  <strong>Overview Note:</strong> {activeDataSet.dataset.summaryText}
                </div>
              )}

            </div>

            {/* KEY TERMS / DIFFICULT WORDS */}
            {activeDataSet.difficultWords && activeDataSet.difficultWords.length > 0 && (
              <div className="space-y-2 pt-2 border-t border-zinc-100 dark:border-zinc-800">
                <span className="text-[10px] font-mono font-bold text-zinc-400 dark:text-zinc-500 uppercase tracking-widest block">
                  Key Technical Terms
                </span>
                <div className="grid sm:grid-cols-2 gap-2">
                  {activeDataSet.difficultWords.map((word, wIdx) => (
                    <div key={wIdx} className="p-2.5 rounded-lg bg-zinc-50 dark:bg-zinc-850/50 border border-zinc-200/50 dark:border-zinc-800 text-xs">
                      <div className="font-bold text-zinc-900 dark:text-white">{word.word}</div>
                      <div className="text-[11px] text-zinc-500 dark:text-zinc-400 mt-0.5">{word.meaning}</div>
                    </div>
                  ))}
                </div>
              </div>
            )}

          </div>
        </div>

        {/* RIGHT COLUMN: INTERACTIVE QUESTION SOLVER (Col-5) */}
        <div className="lg:col-span-5 space-y-6">
          <div className="rounded-2xl border border-zinc-200 bg-white p-6 dark:border-zinc-800 dark:bg-zinc-900 shadow-xs space-y-6">
            
            <div className="flex items-center justify-between border-b border-zinc-100 dark:border-zinc-800 pb-3">
              <h3 className="font-display text-lg font-bold text-zinc-900 dark:text-white flex items-center gap-2">
                <HelpCircle className="h-5 w-5 text-emerald-600 dark:text-emerald-400" />
                <span>Diagnostic Questions</span>
              </h3>
              <span className="text-[10px] font-mono font-bold text-zinc-400">
                {activeDataSet.questions.length} Questions
              </span>
            </div>

            {/* QUESTIONS LIST */}
            <div className="space-y-6">
              {activeDataSet.questions.map((q, idx) => {
                const userGiven = userAnswers[q.id] || "";
                const isCorrect = submitted && userGiven.trim().toLowerCase() === q.answer.trim().toLowerCase();

                return (
                  <div key={q.id} className="space-y-3 p-4 rounded-xl border border-zinc-200/80 dark:border-zinc-800/80 bg-zinc-50/50 dark:bg-zinc-850/30">
                    <div className="flex items-start justify-between gap-2">
                      <span className="font-mono text-xs font-bold text-emerald-600 dark:text-emerald-400">
                        Q{idx + 1}.
                      </span>
                      <p className="flex-1 text-xs font-semibold text-zinc-900 dark:text-white leading-relaxed">
                        {q.question}
                      </p>
                    </div>

                    {/* OPTIONS OR INPUT */}
                    {q.options && q.options.length > 0 ? (
                      <div className="space-y-2 pt-1">
                        {q.options.map(opt => {
                          const isSelected = userGiven === opt;
                          let optionStyle = "border-zinc-200 bg-white dark:border-zinc-800 dark:bg-zinc-900 text-zinc-800 dark:text-zinc-200 hover:border-zinc-300";

                          if (submitted) {
                            if (opt.trim().toLowerCase() === q.answer.trim().toLowerCase()) {
                              optionStyle = "border-emerald-600 bg-emerald-50 dark:bg-emerald-950/30 text-emerald-900 dark:text-emerald-300 font-bold";
                            } else if (isSelected) {
                              optionStyle = "border-red-500 bg-red-50 dark:bg-red-950/30 text-red-900 dark:text-red-300";
                            }
                          } else if (isSelected) {
                            optionStyle = "border-zinc-900 dark:border-white bg-zinc-100 dark:bg-zinc-800 font-bold";
                          }

                          return (
                            <button
                              key={opt}
                              onClick={() => handleOptionSelect(q.id, opt)}
                              disabled={submitted}
                              className={`w-full text-left p-2.5 rounded-lg border text-xs transition cursor-pointer ${optionStyle}`}
                            >
                              {opt}
                            </button>
                          );
                        })}
                      </div>
                    ) : (
                      <div className="pt-1">
                        <textarea
                          value={userGiven}
                          onChange={(e) => setUserAnswers({ ...userAnswers, [q.id]: e.target.value })}
                          disabled={submitted}
                          placeholder="Type your mathematical reasoning or conclusion..."
                          className="w-full rounded-lg border border-zinc-200 dark:border-zinc-800 bg-white dark:bg-zinc-900 p-2.5 text-xs text-zinc-900 dark:text-white outline-none focus:border-emerald-600"
                          rows={2}
                        />
                      </div>
                    )}

                    {/* EXPLANATION ON SUBMISSION */}
                    {submitted && (
                      <div className="mt-2 p-3 rounded-lg bg-emerald-50 dark:bg-emerald-950/30 border border-emerald-200 dark:border-emerald-900/50 text-xs space-y-1">
                        <div className="font-bold text-emerald-800 dark:text-emerald-300 flex items-center gap-1">
                          <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />
                          <span>Correct Answer: {q.answer}</span>
                        </div>
                        <p className="text-[11px] text-zinc-600 dark:text-zinc-350 leading-relaxed">
                          {q.explanation}
                        </p>
                      </div>
                    )}

                  </div>
                );
              })}
            </div>

            {/* ACTION FOOTER */}
            {!submitted ? (
              <button
                onClick={handleSubmitWorksheet}
                className="w-full py-3 rounded-xl bg-zinc-900 hover:bg-zinc-800 dark:bg-zinc-100 dark:hover:bg-zinc-200 dark:text-zinc-900 text-white font-bold text-xs transition cursor-pointer shadow-sm flex items-center justify-center space-x-2"
              >
                <CheckCircle2 className="h-4 w-4 text-emerald-400" />
                <span>Submit & Grade Data Worksheet</span>
              </button>
            ) : (
              scoreResult && (
                <div className="p-4 rounded-xl bg-emerald-50 dark:bg-emerald-950/40 border border-emerald-200 dark:border-emerald-800 text-center space-y-2">
                  <div className="text-2xl font-black font-display text-emerald-700 dark:text-emerald-300">
                    {scoreResult.percentage}% Score ({scoreResult.score}/{scoreResult.max})
                  </div>
                  <p className="text-xs text-zinc-600 dark:text-zinc-350">
                    Gained +{scoreResult.xp} XP! Data reasoning worksheet evaluation logged.
                  </p>
                  <button
                    onClick={() => { setSubmitted(false); setUserAnswers({}); setScoreResult(null); }}
                    className="mt-2 px-4 py-2 rounded-lg border border-emerald-600 text-emerald-700 dark:text-emerald-300 font-bold text-xs hover:bg-emerald-100 dark:hover:bg-emerald-900/40 transition cursor-pointer"
                  >
                    Try Again
                  </button>
                </div>
              )
            )}

          </div>
        </div>

      </div>

    </div>
  );
}
